---
title: "Dengue Situation in Bangladesh"
output: 
  flexdashboard::flex_dashboard:
    logo: img/logo.png
    favicon: img/favicon.png
    theme: flatly
    orientation: rows
    social: menu
    source_code: https://github.com/hossainlab/dengue-situation-dashboard
editor_options: 
  chunk_output_type: console
---

<!----Page 1: Overview Bangladesh---->
```{r child = 'pages/01-overview-bangladesh.Rmd'}
```

<!----Page 2: Dhaka City---->
```{r child = 'pages/02-overview-dhaka-city.Rmd'}
```

<!----Page 3: All Outbreaks---->
```{r child = 'pages/03-comparison-all-outbreaks.Rmd'}
```

<!----Page 3: Last 5 years comparison---->

```{r child = 'pages/last5-years-comparison.Rmd'}
```


<!----Page 4: Top 5 Outbreaks---->
```{r child = 'pages/04-comparison-top5-outbreaks.Rmd'}
```

<!----Page 5: Global Situation---->
```{r child = 'pages/05-global.Rmd'}
```

<!----Page 6: Climate Variables---->


<!----Page 5: Climate Variables---->
```{r child = 'pages/cfr.Rmd'}
```

<!----Page 5: Team---->


<!----About---->
```{r child = 'pages/team.Rmd'}
```

```{r child = 'pages/acknowledgement.Rmd'}
```

```{r child = 'pages/data-sources.Rmd'}
```


