<!----Page 1: Overview - Bangladesh---->

```{r bd-overview-pkg, include=FALSE, warning=FALSE, message=FALSE}
library(flexdashboard)
library(tidyverse)
library(readxl)
library(rio)
library(googlesheets4)
library(denguedatahub)
library(visdat)
library(lubridate) 
library(plotly)
```

<!----Define color for value box---->
```{r, bd-overview-colors, include=FALSE}
confirmed_color <- RColorBrewer::brewer.pal(9, "PuRd")[7]
active_color <-  "#1f77b4"
recovered_color <- "forestgreen"
death_color <- "red"
cfr_color <- "#660708"
active_pct_color <-"#ba181b"
discharged_pct_color <- "#e5383b"
```

<!----Data preparation---->
```{r, bd-overview-case-data}
# cases data 
dengue_cases <- read_sheet("https://docs.google.com/spreadsheets/d/1tqaroRwF40Q6jlaI_aFxAPAgj0yLhFXfua2gzdaZ270/edit?usp=sharing", 
                           range = "Cases")
dengue_cases <- dengue_cases |> mutate(Months = factor(Months, levels = month.name)) 
```

```{r,bd-overview-death-data}
# deaths data 
dengue_deaths <- read_sheet("https://docs.google.com/spreadsheets/d/1tqaroRwF40Q6jlaI_aFxAPAgj0yLhFXfua2gzdaZ270/edit?usp=sharing", 
                            range = "Deaths")
dengue_deaths <- dengue_deaths |> mutate(Months = factor(Months, levels = month.name)) 
```

```{r, bd-overview-transform-case-data}
# transform case data into long format for visualizations 
long_cases_data <- dengue_cases |> 
  pivot_longer(cols = 2:13, names_to = "Year", values_to = "Cases") |> 
  mutate(Months = factor(Months, levels = month.name)) 
```

```{r, bd-overview-transform-deaths-data}
# transform death case data into long format for visualizations 
long_deaths_data <- dengue_deaths |> 
  pivot_longer(cols = 2:10, names_to = "Year", values_to = "Deaths") |> 
  mutate(Months = factor(Months, levels = month.name)) 
```

```{r, bd-overview-join-case-death-data}
# join data 
all_years <- left_join(long_cases_data, long_deaths_data, 
                       by = c("Months", "Year"))
# convert year into factor 
all_years$Year <- as.factor(all_years$Year)
```

```{r, bd-overview-filter-data-for-2023}
# Monthly dengue cases for 2023 
long_cases_data_23 <- long_cases_data|> 
  filter(Year == 2023)

long_deaths_data_23 <- long_deaths_data|> 
  filter(Year == 2023)
```

```{r, bd-overview-join-data-for-2023}
# join data for monthly cases 
data23 <- left_join(long_cases_data_23, long_deaths_data_23, 
                    by = c("Months", "Year"))

data23$Year <- as.factor(data23$Year)
```


```{r, bd-overview-daily-data-2023}
# daily data for 2023 
daily_data_23_url <- "https://docs.google.com/spreadsheets/d/1QgYLR4FW0f9MxiH0GDZm2_5tZOdAlLZAKT4-8Tz9rwQ/edit?usp=sharing"

# read multiple data sheets 
daily_data_23 <- daily_data_23_url |> 
  sheet_names() |> 
  set_names() |> 
  map_df(read_sheet, ss = daily_data_23_url, .id = "Month") |> 
  mutate(Month = factor(Month, levels = month.name)) |> 
  mutate(Date = as.Date(Date))
```


Bangladesh {data-navmenu="Summary"}
===================================================================

Row { data-width=150 }
-------------------------------------------------------------------
### Confirmed Cases {.value-box}

```{r, bd-overview-confirmed}
confirmed <- format(sum(daily_data_23$Cases, na.rm = T), big.mark = ",")
valueBox(value = confirmed, 
         caption = "Total Confirmed Cases in 2023", 
         color = confirmed_color, 
         icon = "fa-virus")
```


### Confirmed Deaths {.value-box}
```{r, bd-overview-deaths}
deaths <- format(sum(daily_data_23$Deaths, na.rm = T), big.mark = ",")
valueBox(value = deaths, 
         caption = "Total Death Cases in 2023", 
         color = death_color, 
         icon = "fa-exclamation-triangle")
```

### Recovered Cases {.value-box}
```{r, bd-overview-recovered}
recovered <- format(sum(daily_data_23$Recovered, na.rm = T), big.mark = ",")
valueBox(value = recovered, 
         caption = "Total Recovered Cases in 2023", 
         color = recovered_color, 
         icon = "fa-check-circle")
```

### Active Cases {.value-box}
```{r, bd-overview-active}
daily_data_23$Active <- daily_data_23$Cases - daily_data_23$Deaths - daily_data_23$Recovered
active <- format(sum(daily_data_23$Active, na.rm = T), big.mark = ",")
valueBox(value = active, 
         caption = "Total Active Cases in 2023", 
         color = active_color, 
         icon = "fa-skull")
```


### Case Fatality Rate (CFR) {.value-box}
```{r, bd-overview-cfr}
cfr <-  round(sum(daily_data_23$Deaths, na.rm = T) / sum(daily_data_23$Cases, na.rm = T) * 100, 2)

valueBox(value = cfr, 
         caption = "Case Fatality Rate (CFR) in 2023", 
         color = cfr_color, 
         icon = "fa-heart-broken")
```

### Percentage of Discharged {.value-box}
```{r, bd-overview-discharged_pct}
discharged_pct <- format(sum(daily_data_23$Recovered, na.rm = T)/sum(daily_data_23$Cases, na.rm = T) * 100, digit = 2)

valueBox(value = discharged_pct, 
         caption = "% of Discharged in 2023", 
         color = discharged_pct_color, 
         icon = "fa-check-square")
```


### Percentage of Active Cases {.value-box}
```{r, bd-overview-active_pct}

daily_data_23$Active <- daily_data_23$Cases - daily_data_23$Deaths - daily_data_23$Recovered

active_pct <- format(sum(daily_data_23$Active, na.rm = T)/sum(daily_data_23$Cases, na.rm = T) * 100, digit = 2)
valueBox(value = active_pct, 
         caption = "% of Active Cases in 2023", 
         color = active_pct_color, 
         icon = "fa-exclamation-circle")
```


Row
-----------------------------------------------------------------------
### Monthly Dengue Cases, Deaths, and Recovered in 2023
```{r, include=FALSE}
monthly_data_23 <- daily_data_23 |> 
  group_by(Month) |> 
  summarise(TotalCases = sum(Cases), 
            TotalDeaths = sum(Deaths), 
            TotalRecovered = sum(Recovered))
```

```{r}
# Viz 1: Monthly Dengue Cases, Deaths, and Recovered 
plot_ly(data = monthly_data_23, x = ~Month, type = 'scatter', mode = 'lines+markers', 
        name = 'Cases', y = ~TotalCases) |> 
  add_trace(y = ~TotalDeaths, name = "Deaths", type = 'scatter', mode = 'lines+markers') |> 
  add_trace(y = ~TotalRecovered, name = "Recovered", type = 'scatter', mode = 'lines+markers') |> 
  layout(title = " Monthly Trends: Dengue Cases, Deaths, and Recoveries", 
         xaxis = list(title = 'Months'),
         yaxis = list(title = 'Cases'), 
         legend = list(orientation = "h", 
                       xanchor = "center", 
                       x = 0.5, 
                       y= -0.3))

```



### Number of Dengue Cases by Month in 2023

```{r}
# Viz 2: Number of Dengue Cases
plot_ly(data = data23, x = ~Months)  |> 
  add_bars(y = ~Cases, name = 'Confirmed Cases') |> 
  add_trace(y = ~Cases, type = 'scatter', mode = 'lines+markers', name = "Trends") |> 
  layout(title = "Monthly Dengue Cases",
         xaxis = list(title = 'Month'),
         yaxis = list(title = 'Confirmed Cases'), 
         legend = list(orientation = "h", 
                       xanchor = "center", 
                       x = 0.5, 
                       y= -0.3))
```

Row
-----------------------------------------------------------------------

### Number of Death Cases by Month in 2023
```{r}
# Viz 3: Number of Death Cases in 2023
plot_ly(data = data23, x = ~Months) |> 
  add_bars(y = ~Deaths, name = 'Confirmed Deaths', marker = list(color = 'black')) |> 
  add_trace(y = ~Deaths, type = 'scatter', mode = 'lines+markers', name = "Trends") |> 
  layout(title = "Monthly Dengue Deaths",
         xaxis = list(title = 'Month'),
         yaxis = list(title = 'Death Cases'), 
         legend = list(orientation = "h", 
                       xanchor = "center", 
                       x = 0.5, 
                       y = -0.3))
```

### Distribution between Recovery and Death
```{r}
plot_ly(data = daily_data_23,
                x = ~ Date,
                y = ~ Recovered, 
                name = 'Recovered', 
                fillcolor = recovered_color,
                type = 'scatter',
                mode = 'none', 
                stackgroup = 'one', groupnorm = 'percent') |> 
add_trace( y = ~ Deaths, 
                     name = "Death",
                     fillcolor = death_color) |> 
layout(title = "",
                 legend = list(x = 0.75, y = 0.05),
                 ticksuffix = "%",
                 yaxis = list(title = "Recoverd / Death Dist (%)", 
                              showgrid = FALSE,
                              hoverformat = ".2f",
                              ticksuffix = "%"),
                 xaxis = list(title = "Source: ", showgrid = FALSE),
                 hovermode = "compared")
```







<!-- ### Month-wise Case Fatality Rate in Bangladesh  -->
<!-- ```{r, bd-overview-cfr-data} -->
<!-- monthly_cfr_data_23 <- daily_data_23 |>  -->
<!--   group_by(Month) |>  -->
<!--   summarise(TotalCases = sum(Cases, na.rm = T),  -->
<!--             TotalDeaths = sum(Deaths, na.rm = T),  -->
<!--             CFR = round(sum(Deaths, na.rm = T) / sum(Cases, na.rm = T) * 100, 2))  -->
<!-- ``` -->
<!-- ```{r, bd-overview-cfr-data-viz-4} -->
<!-- # Viz 4: Number of Death Cases in 2023 -->
<!--  plot_ly(monthly_cfr_data_23, x = ~Month, y = ~CFR, type = 'bar', name = "Case Fatality Rate", marker = list(color = '#d8b365'))  |>  -->
<!--   add_trace(y = ~CFR, name = "Trend", type = 'scatter', mode = 'lines+markers', line = list(color = '#252525')) |>  -->
<!--   layout(title = "Monthly Dengue Case Fatality Rate", -->
<!--          xaxis = list(title = 'Month'), -->
<!--          yaxis = list(title = 'Case Fatality Rate'),  -->
<!--          legend = list(orientation = "h",  -->
<!--                        xanchor = "center",  -->
<!--                        x = 0.5,  -->
<!--                        y = -0.3)) -->

<!-- ``` -->


<!-- ### Affected Case by Agre Group [01 Jan to 12 Sep 2023] -->

<!-- ```{r, demographics-cases-data, include=FALSE} -->
<!-- # data -->
<!-- demographic_cases_data <- read_sheet("https://docs.google.com/spreadsheets/d/1is72sf_4XUFCwJqhdWwveE00XNuxZ0pVKfN3OsmEnFI/edit?usp=sharing", range = "Age-Sex-Distribution[CountryLevelCases]") -->

<!-- demographic_cases_data$AgeGroup <- as.factor(demographic_cases_data$AgeGroup) -->
<!-- ``` -->

<!-- ```{r, bd-overview-cases-age-group} -->
<!-- # Viz 5: Dengue Cases by Age Group -->
<!-- plot_ly(data = demographic_cases_data, x = ~AgeGroup, y = ~TotalCases, type = "bar", name = "Cases",marker = list(color = "#bf812d"))  |>  -->
<!--   layout(title = "Dengue Cases by Age Group", -->
<!--          xaxis = list(title = "Age Group", categoryorder='category ascending',  -->
<!--                       tickangle=60), -->
<!--          yaxis = list(title = "Number of Dengue Cases")) -->
<!-- ``` -->
<!-- ### Dengue Death Report by Age Group [01 Jan to 12 Sep 2023] -->

<!-- ```{r, demographics-deaths-data, include=FALSE} -->
<!-- # data -->
<!-- demographic_deaths_data <- read_sheet("https://docs.google.com/spreadsheets/d/1is72sf_4XUFCwJqhdWwveE00XNuxZ0pVKfN3OsmEnFI/edit?usp=sharing", range = "Age-Sex-Distribution[CountryLevelDeaths]") -->

<!-- demographic_deaths_data$AgeGroup <- as.factor(demographic_deaths_data$AgeGroup) -->
<!-- ``` -->


<!-- ```{r, bd-overview-deaths-age-group} -->
<!-- # Viz 6: Dengue Deaths by Age Group -->
<!-- plot_ly(data = demographic_deaths_data, x = ~AgeGroup, y = ~TotalDeaths, type = "bar", name = "Cases",marker = list(color = "#d6604d")) |>  -->
<!--   layout(title = "Dengue Deaths by Age Group", -->
<!--          xaxis = list(title = "Age Group", categoryorder='category ascending', tickangle=60), -->
<!--          yaxis = list(title = "Number of Deaths Cases")) -->
<!-- ``` -->



