
Top 5 - Outbreaks{data-navmenu="Comparisons"}
===================================================================

Row
-------------------------------------------------------------------
### Top 5 Dengue Outbreaks Cases by Year and Month 

```{r, include=FALSE}
# Top 5 outbreaks by month and year in Bangladesh 
top5_outbreaks_month_year <- all_years |> 
  group_by(Year, Months) |> 
  summarise(TotalCases = sum(Cases), 
            TotalDeaths = sum(Deaths)) |> 
  filter(Year %in% c(2018, 2019, 2021, 2022, 2023))
```

```{r, include=FALSE}
# Top 5 outbreaks by year in Bangladesh 
top5_outbreaks_year <- all_years |> 
  group_by(Year) |> 
  summarise(TotalCases = sum(Cases), 
            TotalDeaths = sum(Deaths)) |> 
  filter(Year %in% c(2018, 2019, 2021, 2022, 2023))
```


```{r}
# Top 5 Dengue Outbreaks by Year and Month 
plot_ly(data = top5_outbreaks_month_year, x = ~Months, y = ~TotalCases, type = 'scatter', mode = 'lines+markers', color = ~Year) |> 
  layout(title = "Top 5 Dengue Outbreaks Cases by Year and Month",
         xaxis = list(title = "Month"),
         yaxis = list(title = "Total Cases"), 
         legend = list(title=list(text='<b> Years </b>')))
```


### Top 5 Dengue Outbreaks Cases by Year

```{r}
# Year-wise dengue cases 
plot_ly(data = top5_outbreaks_year, x = ~Year)  |> 
  add_bars(y = ~TotalCases, name = 'Cases', marker = list(color = "#5ec962")) |> 
  layout(title = 'Top 5 Dengue Outbreaks Cases by Year', 
         xaxis = list(title = 'Year', categoryorder = "trace"),
         yaxis = list(title = 'Number of Cases'))

```


Row
-------------------------------------------------------------------
### Top 5 Dengue Outbreaks Deaths by Month and Year

```{r}
plot_ly(data = top5_outbreaks_month_year, x = ~Months, y = ~TotalDeaths, type = 'scatter', mode = 'lines+markers', color = ~Year) |> 
  layout(title = "Monthly Total Death Cases for top 5 Outbreaks",
         xaxis = list(title = "Month"),
         yaxis = list(title = "Total Cases"), 
         legend = list(title=list(text='<b> Years </b>')))
```


### Top 5 Dengue Outbreaks Deaths by Year

```{r}
# Year-wise dengue cases 
plot_ly(data = top5_outbreaks_year, x = ~Year)  |> 
  add_bars(y = ~TotalDeaths, name = 'Cases', marker = list(color = "#21918c")) |> 
  layout(title = 'Year-wise Dengue Deaths', 
         xaxis = list(title = 'Year', categoryorder = "trace"),
         yaxis = list(title = 'Number of Death Cases'))
```