
Global Situation
===================================================================

Row
-------------------------------------------------------------------
### Level of Dengue Risk around the Globe 

```{r, include=FALSE}
tab1 <- level_of_risk %>% group_by(region, level_of_risk) %>%
  summarise(count = n(), .groups = 'drop') 
knitr::kable(tab1)

```

```{r}
# Summarize and Visualize level_of_riskdata
p1 <- ggplot(tab1, aes(region, count)) + 
  geom_bar(aes(fill = level_of_risk), stat = "identity", position = "dodge")+
  labs(title = "Level of Dengue risk around the world",
       subtitle = "The level of risk in the context of dengue refers to the likelihood of dengue outbreaks happening in various regions worldwide.", 
       x = "Region",
       y = "Number of countries", 
       caption = "by Jubayer Hossain, Data Source: denguedatahub")+ 
  guides(fill = guide_legend(title = "Level of Risk"))+
  scale_fill_brewer(palette = "Dark2")+ 
  theme(legend.position = "top") 
ggplotly(p1)
```

### Presence of Dengue Incidence in 2017
```{r}
# Presence of dengue incidence in 2019
worlddata2019 <- dplyr::filter(world_annual, year == 2017)
p2 <- ggplot(worlddata2019, aes(x = long,
                          y = lat,
                          group=group,
                          fill = dengue.present)) +
  geom_polygon(color = "black") +
  labs(title = "Presence of dengue incidence in 2017", 
       subtitle = "Dengue Incidence in 2017: A Global Health Challenge", 
       x = "Longitude",
       y = "Latitude", 
       caption = "by Jubayer Hossain, Data Source: denguedatahub") +
  guides(fill = guide_legend(title = "Dengue Present?"))+
  theme(legend.position = "top") + 
  scale_fill_brewer(palette = "Set2") 

ggplotly(p2)
```

Row
-------------------------------------------------------------------
### Presence of Dengue Incidence in 2018
```{r}
# Presence of dengue incidence in 2019
worlddata2019 <- dplyr::filter(world_annual, year == 2018)
p3 <- ggplot(worlddata2019, aes(x = long,
                          y = lat,
                          group=group,
                          fill = dengue.present)) +
  geom_polygon(color = "black") +
  labs(title = "Presence of dengue incidence in 2018", 
       subtitle = "Dengue Incidence in 2018: A Global Health Challenge", 
       x = "Longitude",
       y = "Latitude", 
       caption = "by Jubayer Hossain, Data Source: denguedatahub") +
  guides(fill = guide_legend(title = "Dengue Present?"))+
  theme(legend.position = "top") + 
  scale_fill_brewer(palette = "Set1") 

ggplotly(p3)
```


### Presence of Dengue Incidence in 2019
```{r}
# Presence of dengue incidence in 2019
worlddata2019 <- dplyr::filter(world_annual, year == 2019)
p4 <- ggplot(worlddata2019, aes(x = long,
                          y = lat,
                          group=group,
                          fill = dengue.present)) +
  geom_polygon(color = "black") +
  labs(title = "Presence of dengue incidence in 2019", 
       subtitle = "Dengue Incidence in 2019: A Global Health Challenge", 
       x = "Longitude",
       y = "Latitude", 
       caption = "by Jubayer Hossain, Data Source: denguedatahub") +
  guides(fill = guide_legend(title = "Dengue Present?"))+
  theme(legend.position = "top") + 
  scale_fill_brewer(palette = "Greens") 

ggplotly(p4)
```


